[package]
name = "cli"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
path = "src/cli.rs"
name = "remote_server_cli"

[dependencies]

repository = { path = "../repository" }
util = { path = "../util" }
service = { path = "../service" }
server = { path = "../server" }
graphql = { path = "../graphql" }

anyhow = { workspace = true }
async-graphql = { workspace = true }
clap = { version = "3.1.8", features = ["derive"] }
chrono = { version = "0.4.38" }
diesel = { version = "2.1.5", default-features = false, features = ["chrono"] }
log = "0.4.14"
serde = "1.0.126"
serde_json = "1.0.66"
simple-log = { version = "1.6" }
tokio = { version = "1.17.0", features = ["macros"] }

[dev-dependencies]
actix-rt = "2.6.0"
tokio = { version = "1.17.0", features = ["time", "rt-multi-thread", "macros"] }

[features]
default = ["sqlite"]
sqlite = ["server/sqlite"]
postgres = ["server/postgres"]
