[profile.release]
strip = true

[workspace.dependencies]
# dependencies used in graphql crates:
actix-web = { version = "4.0.1", default-features = false, features = [
  "macros",
  "rustls",
] }
actix-multipart = "0.6.1"
anymap = "0.12"
async-graphql = { version = "3.0.35", features = ["dataloader", "chrono"] }
async-graphql-actix-web = "3.0.35"
async-trait = "0.1.30"
chrono = { version = "0.4.38", features = ["serde"] }
reqwest = { version = "0.12", features = [
  "json",
  "rustls-tls",
  "multipart",
  "blocking",
], default-features = false }
serde = "1.0.126"
serde_json = "1.0.66"
thiserror = "1.0.30"
# dev dependencies used in graphql crates:
actix-rt = "2.6.0"
assert-json-diff = "2.0.1"
async-std = "1.12.0"
rand = "0.8.5"
anyhow = "1.0.56"
actix-files = "0.6.0"

[workspace]

members = [
  "android",
  "report_builder",
  "repository",
  "graphql",
  "server",
  "service",
  "util",
  "graphql/core",
  "graphql/types",
  "graphql/requisition",
  "graphql/requisition_line",
  "graphql/stocktake",
  "graphql/stocktake_line",
  "graphql/invoice",
  "graphql/invoice_line",
  "graphql/location",
  "graphql/general",
  "graphql/batch_mutations",
  "graphql/repack",
  "cli",
  "windows",
]
