on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "server/**"
  workflow_dispatch:

name: CI

jobs:
  build_and_test:
    name: Remote Server Tests (sqlite)
    runs-on: self-hosted
    timeout-minutes: 25
    env:
      CARGO_TARGET_DIR: target/sqlite
      PATH: /$home/.cargo/bin/rustup:/usr/bin/:$PATH
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=sqlite --manifest-path server/Cargo.toml
  build_and_test_pg:
    name: Remote Server Tests (postgres)
    runs-on: self-hosted
    timeout-minutes: 25
    env:
      CARGO_TARGET_DIR: target/postgres
      PATH: /$home/.cargo/bin/rustup:$PATH
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=postgres --manifest-path server/Cargo.toml
