on:
  push:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "server/**"
  workflow_dispatch:

name: CI

jobs:
  build_and_test:
    name: Remote Server Tests (sqlite)
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=sqlite --manifest-path server/Cargo.toml
